### ISSUE TITLE
[help wanted] Cannot read property 'sys' of undefined

### ISSUE THREAD

**Issue by fengxin930926134** [akeboshi1/Phaser-wx#1]
如图，我尝试用该项目实现一个官方的例子，但是在添加scene时出错了，请问应该怎么解决这个问题，是我使用方式不对还是兼容还未完善。
![QQ截图20221101162653](https://user-images.githubusercontent.com/38252526/199195361-d9717e8d-a396-4576-8fcb-0e6661bf6ac8.png)

**Comment by fengxin930926134** [comment]
我尝试实现的例子是 https://github.com/ourcade/infinite-jumper-template-phaser3.git

**Comment by akeboshi1** [comment]
> 我尝试实现的例子是 https://github.com/ourcade/infinite-jumper-template-phaser3.git

你确认下你添加场景代码是否有问题，看报错应该是找不到scene，你可以把添加场景的代码贴上来

**Comment by akeboshi1** [comment]
> 我尝试实现的例子是 https://github.com/ourcade/infinite-jumper-template-phaser3.git

可能你需要在scene的构造函数中，给每个scene添加一个key的默认值，否则在微信环境下，scene.key的默认值都是default，会产生歧义
