### ISSUE TITLE
Spritesheet无法load，楼主有准备加一下吗？

### ISSUE THREAD

**Issue by zhuhengtan** [akeboshi1/Phaser-wx#2]
RT，刚看上phaser这框架，还不太会改源码orz

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by akeboshi1** [comment]
> RT，刚看上phaser这框架，还不太会改源码orz
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

ok，这两天把sprite给加下

**Comment by akeboshi1** [comment]
如果在本地需要load image/json/binary/atlas/draonBone时，要在xhrsetting参数中加入wechatDebug:true，以便正常本地调试
如此：
![image](https://user-images.githubusercontent.com/18412751/201458820-c67ffd67-90e2-4e6e-a95c-0f79af21afea.png)

**Comment by zhuhengtan** [comment]
> 如果在本地需要load image/json/binary/atlas/draonBone时，要在xhrsetting参数中加入wechatDebug:true，以便正常本地调试 如此： ![image](https://user-images.githubusercontent.com/18412751/201458820-c67ffd67-90e2-4e6e-a95c-0f79af21afea.png)

OK，感觉可以把这个加到readme里面，大家都能看见
