### ISSUE TITLE
Phaser 3 以及 Phaser Adapter 有源码吗？

### ISSUE THREAD

**Issue by LittleBoy1993** [akeboshi1/Phaser-wx#4]
如题，想问对 Phaser 3 以及你自己打包的 Phaser Adapter 有源码吗？
我这边有一些小问题要在源码的基础上再修改一些，想看看这部分的源码来自己打包构建。
Phaser 3 的话想看对 Phaser 源码改造的部分，Adapter 不知道有没有源码。

**Comment by MacrazdHao** [comment]
同求，搞了一个多星期，没搞出个能完整用的自编译版本T T

**Comment by LittleBoy1993** [comment]
> 同求，搞了一个多星期，没搞出个能完整用的自编译版本T T

https://github.com/LittleBoy1993/phaser/tree/wechat
可以参考一下

Phaser Adapter 可以搜一下，是开源的，Star 最多的那个就是。

**Comment by akeboshi1** [comment]
抱歉有一段时间没关注github，这两个文件在项目libs文件夹下，直接在js上改动，然后压缩即可用。如果有可行的修改可以往上面提交，我会合并到项目上去。
另外，可以关注下https://github.com/akeboshi1/PhaserResRecycle 这个项目，里面做了一些对资源回收的处理，由于phaser没有处理资源回收的问题，可能会导致小游戏内存的问题，只是当做一个借鉴，不能直接运用到wx项目中
